"""Hindsight's declared config surface — rendered by the generic desktop panel."""

from plugins.memory.config_schema import (
    KIND_BOOL,
    KIND_JSON,
    KIND_NUMBER,
    KIND_SECRET,
    KIND_SELECT,
    KIND_TEXT,
    ProviderConfigSchema,
    ProviderField,
    ProviderFieldOption,
)

CONFIG_SCHEMA = ProviderConfigSchema(
    name="hindsight",
    label="Hindsight",
    fields=(
        ProviderField(
            key="mode",
            label="Mode",
            kind=KIND_SELECT,
            default="cloud",
            description="How Hermes connects to Hindsight.",
            options=(
                ProviderFieldOption(
                    "cloud",
                    "Cloud",
                    "Hindsight Cloud API (lightweight, just needs an API key)",
                ),
                ProviderFieldOption(
                    "local_external",
                    "Local External",
                    "Connect to an existing Hindsight instance",
                ),
            ),
            inline=True,
        ),
        ProviderField(
            key="api_key",
            label="API key",
            kind=KIND_SECRET,
            env_key="HINDSIGHT_API_KEY",
            description="Used to authenticate with the Hindsight API.",
            placeholder="Enter Hindsight API key",
            inline=True,
        ),
        ProviderField(
            key="api_url",
            label="API URL",
            kind=KIND_TEXT,
            default="https://api.hindsight.vectorize.io",
            aliases=("apiUrl",),
            env_fallbacks=("HINDSIGHT_API_URL",),
            inline=True,
        ),
        ProviderField(
            key="bank_id",
            label="Bank ID",
            kind=KIND_TEXT,
            default="hermes",
            aliases=("bankId",),
            inline=True,
        ),
        ProviderField(
            key="recall_budget",
            label="Recall budget",
            kind=KIND_SELECT,
            default="mid",
            aliases=("budget",),
            options=(
                ProviderFieldOption("low", "low"),
                ProviderFieldOption("mid", "mid"),
                ProviderFieldOption("high", "high"),
            ),
            inline=True,
        ),
        ProviderField(
            key="recall_auto_route",
            label="Automatic recall routing",
            kind=KIND_BOOL,
            default="false",
            description="Opt in to configuration-driven recall routes.",
            info="Routes are matched by chat identity or configured keywords; no product-specific routes are built in.",
            group="Recall routing",
        ),
        ProviderField(
            key="recall_auto_route_fail_open",
            label="Allow unfiltered route fallback",
            kind=KIND_BOOL,
            default="false",
            description="Allow an empty tagged route to retry without positive tags.",
            info="This is off by default. Exclusion tags remain enforced when the final fallback runs.",
            group="Recall routing",
        ),
        ProviderField(
            key="recall_routes",
            label="Recall routes",
            kind=KIND_JSON,
            default="",
            description="Ordered JSON route definitions using chat_ids, chat_names, keywords, tags, types, exclusions, and result caps.",
            info="Route names and tags are user-defined. Use fallback_tags for a tag-scoped widening step; unfiltered fallback still requires the separate opt-in.",
            group="Recall routing",
        ),
        ProviderField(
            key="recall_max_results",
            label="Maximum recall results",
            kind=KIND_NUMBER,
            default="0",
            description="Global result cap after route filtering; 0 means unlimited.",
            group="Recall routing",
        ),
    ),
)
